# Usar a imagem oficial do PostgreSQL como base
FROM postgres:13

# Definir o nome do banco de dados que será criado
ENV POSTGRES_DB=my_database

# Definir o nome do usuário que será criado
ENV POSTGRES_USER=my_user

# Definir a senha do usuário
ENV POSTGRES_PASSWORD=123457

