# Etapa 1: Definir a imagem base
FROM node:14

# Etapa 2: Definir o diretório de trabalho
WORKDIR /app

# Etapa 3: Copiar o package.json e o package-lock.json para instalar as dependências
COPY package*.json ./

# Etapa 4: Instalar as dependências do backend
RUN npm install

# Etapa 5: Copiar os arquivos da aplicação
COPY . .

# Etapa 6: Expor a porta que o Express usará
EXPOSE 5000

# Etapa 7: Definir o comando para rodar a aplicação
CMD ["node", "index.js"]
