# Etapa 1: Definir a imagem base
FROM node:14-alpine AS build

# Etapa 2: Definir o diretório de trabalho
WORKDIR /app

# Etapa 3: Copiar o package.json e o package-lock.json para instalar as dependências
COPY package*.json ./

# Etapa 4: Instalar as dependências do React
RUN npm install

# Etapa 5: Copiar os arquivos da aplicação
COPY . .

# Etapa 6: Construir a aplicação para produção
RUN npm run build

# Etapa 7: Expor a porta que o React usará
EXPOSE 3000

# Etapa 8: Definir o comando para rodar a aplicação
CMD ["npm", "start"]
