# Usar uma imagem base do Docker Hub (imagem oficial do Node.js)
FROM node:14

# Definir o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copiar os arquivos de configuração do projeto
COPY package*.json ./

# Instalar as dependências do projeto
RUN npm install

# Copiar o restante do código da aplicação
COPY . .

# Expor a porta em que o aplicativo vai rodar
EXPOSE 5000

# Definir o comando para rodar o aplicativo
CMD ["npm", "start"]
