# Etapa 1: Definir a imagem base do PostgreSQL
FROM postgres:13

# Etapa 2: Configurar variáveis de ambiente
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=admin123
ENV POSTGRES_DB=appdb

# Etapa 3: Expor a porta padrão do PostgreSQL
EXPOSE 5432

# O PostgreSQL já inicia automaticamente na imagem
