# Usar a imagem oficial do PostgreSQL
FROM postgres:13

# Configurações iniciais do banco de dados (opcional, apenas exemplo)
# Variáveis de ambiente para configurar o banco de dados
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD=password
ENV POSTGRES_DB=mydatabase

# Expor a porta padrão do PostgreSQL
EXPOSE 5432
