name: Deploy to Production

on:
  push:
    branches:
      - main
      
jobs:
  publish_docker_images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Front-End Image
        run: |
          docker build -f Dockerfile.frontend -t ${{ secrets.DOCKER_USERNAME }}/frontend-image .
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend-image

      - name: Build and Push Back-End Image
        run: |
          docker build -f Dockerfile.backend -t ${{ secrets.DOCKER_USERNAME }}/backend-image .
          docker push ${{ secrets.DOCKER_USERNAME }}/backend-image

      - name: Build and Push Database Image
        run: |
          docker build -f Dockerfile.database -t ${{ secrets.DOCKER_USERNAME }}/database-image .
          docker push ${{ secrets.DOCKER_USERNAME }}/database-image

  deploy_to_production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Simulate Deploy to Production
        run: |
          echo "Simulando o deploy para o ambiente de produção..."
          # Aqui, você pode adicionar comandos para fazer deploy real se necessário
