version: '3.8'

services:
  db:
    image: postgres:13
    container_name: my_postgres_container
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Mapeando a porta 5432 do contêiner para a porta 5432 do host (default do PostgreSQL)

volumes:
  pg_data:
    driver: local
